#spring:
#  application:
#    name: Apollo Fitness
#  jpa:
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/healthclub?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root
#
app:
  cors:
    allowed-origins: http://localhost:3000
         # allowed-origins: http://52.90.170.253:3000  #address of the frontend server


#logging:
#  level:
#    org.springframework.security: DEBUG
